import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '../globals.css';
import ToastProvider from '@/providers/ToastProvider';
import Navbar from './_components/navbar/Navbar';
import Footer from './_components/Footer';

const font = Roboto({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        <ToastProvider />
        <Navbar />
        {children}
        <Footer />
      </>
  );
}
